use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::handlers::health::health_handler,
        crate::handlers::host::sysinfo_handler,
        crate::handlers::host::sysinfo_stream_handler,
        crate::handlers::config::config_status_handler,
        crate::handlers::config::hardware_detect_handler,
        crate::handlers::config::save_setup_config_handler,
        crate::handlers::runtimes::runtimes_handler,
        crate::handlers::runtimes::install_runtime_handler,
        crate::handlers::runtimes::install_stream_handler,
        crate::handlers::runtimes::uninstall_runtime_handler,
        crate::handlers::runtime_manifests::get_runtime_manifests_handler,
        crate::handlers::runtime_manifests::get_runtime_manifest_by_id_handler,
        crate::handlers::models::available_models_handler,
        crate::handlers::models::get_models_handler,
        crate::handlers::models::create_model_handler,
        crate::handlers::models::update_model_handler,
        crate::handlers::models::delete_model_handler,
        crate::handlers::models::load_model_handler,
        crate::handlers::models::swap_model_handler,
        crate::handlers::models::unload_model_handler,
        crate::handlers::models::unload_all_models_handler,
        crate::handlers::models::get_running_models_handler,
        crate::handlers::chats::get_chats_handler,
        crate::handlers::chats::create_chat_handler,
        crate::handlers::chats::update_chat_handler,
        crate::handlers::chats::delete_chat_handler,
        crate::handlers::chats::get_chat_messages_handler,
        crate::handlers::chats::create_chat_message_handler,
        crate::handlers::chats::update_chat_message_handler,
        crate::handlers::chats::delete_chat_message_handler,
        crate::handlers::chats::clear_chat_messages_handler,
        crate::handlers::settings::get_all_settings_handler,
        crate::handlers::settings::get_setting_handler,
        crate::handlers::settings::update_settings_handler,
        crate::handlers::settings::delete_setting_handler,
        crate::handlers::openai_proxy::v1_models_handler,
        crate::handlers::openai_proxy::v1_model_by_id_handler,
        crate::handlers::openai_proxy::v1_chat_completions_doc,
        crate::handlers::openai_proxy::v1_completions_doc,
        crate::handlers::openai_proxy::v1_embeddings_doc,
    ),
    components(
        schemas(
            crate::config::ConfigStatus,
            crate::handlers::config::SaveConfigRequest,
            crate::handlers::config::SaveConfigResponse,
            crate::runtimes::hardware::HardwareReport,
            crate::handlers::host::SysInfoResponse,
            crate::handlers::host::CpuInfo,
            crate::handlers::host::RamInfo,
            crate::handlers::host::OsInfo,
            crate::handlers::host::VramInfo,
            crate::handlers::host::HostMetricsTick,
            crate::runtimes::installer::RuntimeItem,
            crate::runtimes::installer::InstallProgress,
            crate::handlers::runtimes::InstallRuntimeRequest,
            crate::handlers::runtimes::OperationResponse,
            crate::runtimes::manifest_loader::RuntimeManifest,
            crate::runtimes::manifest_loader::ManifestFlag,
            crate::runtimes::manifest_loader::DownloadTarget,
            crate::runtimes::model_scanner::ModelItem,
            crate::db::models::ModelRecord,
            crate::db::models::CreateModelPayload,
            crate::runtimes::process_manager::ModelState,
            crate::runtimes::process_manager::RunningModelStatus,
            crate::db::chats::ChatRecord,
            crate::db::chats::ChatMessageRecord,
            crate::db::chats::CreateChatPayload,
            crate::db::chats::UpdateChatPayload,
            crate::db::chats::CreateChatMessagePayload,
            crate::db::chats::UpdateChatMessagePayload,
            crate::handlers::openai_proxy::OpenAiModelItem,
            crate::handlers::openai_proxy::OpenAiModelList,
            crate::handlers::openai_proxy::OpenAiChatCompletionRequest,
            crate::handlers::openai_proxy::OpenAiCompletionRequest,
            crate::handlers::openai_proxy::OpenAiEmbeddingRequest,
        )
    ),
    tags(
        (name = "OpenAI Compatibility", description = "OpenAI compatible /v1 API endpoints (chat, completions, embeddings, models)"),
        (name = "Health", description = "Application health check endpoints"),
        (name = "Host", description = "System hardware & resource monitoring endpoints"),
        (name = "Config", description = "Server configuration, directories & hardware detection"),
        (name = "Runtimes", description = "LLM execution runtime discovery, installation & management"),
        (name = "Models", description = "Model registry, scanning, and process lifecycle (load, swap, unload)"),
        (name = "Chats", description = "Local chat session and message management"),
        (name = "Settings", description = "Key-value persistent application settings")
    ),
    info(
        title = "Monolai API",
        version = "0.1.0",
        description = "REST API for Monolai — Local LLM management, hardware monitoring, and OpenAI-compatible proxy.",
        license(name = "MIT")
    )
)]
pub struct ApiDoc;