[package]
name = "monolai-gui"
version = "0.1.2"
edition = "2021"

[dependencies]
eframe = { version = "0.29", default-features = false, features = [
    "default_fonts",
    "glow",
    "wayland",
    "x11",
] }
tray-icon = { version = "0.26", default-features = false, features = ["ksni"] }
open = "5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
dirs = "5.0"
ureq = { version = "2.10", default-features = false }
rfd = "0.15"
image = { version = "0.25", default-features = false, features = ["png"] }
libc = "0.2"
dark-light = "3.0"
auto-launch = "0.6.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"
